### PR TITLE
Add support for mapping mixed types

### PR DESCRIPTION
**Pull request by rmohr**
Hi, 

I wanted to map my uuid.UUID type  from a field "UUID" to a string field called "UUID". Since this was not possible I added a feature to add custom converters for specific types.

I also added some unit tests. It seems to work but I want to write a little bit more tests and I have some documentation TODOs. Before I do the polishing I wanted to share it with you, to hear what you think about it.

### CODE REVIEW

**Comment by rmohr** [comment]
@jeevatkm is this of interest for you?

**Comment by jeevatkm** [comment]
I like this idea. I got stuck with my personal priorities right now. Thanks for your patience.

I will surely get back to this as soon as possible. Thanks.

**Comment by jeevatkm** [comment]
@rmohr I have went through your implementation. Nice work 👍 

Can you please delete IDE file `.idea/vcs.xml` from repo? If you would like to give final touch on this PR, please go ahead. 

I'm planning to merge this PR into master and bumping version to `0.5`. Release date I will let you know later.

**Comment by rmohr** [comment]
@jeevatkm thx for looking int the PR. I removed the file and pushed two more commits on it. One makes sure that the custom converters work for slices and maps and the third one allows copyVal to propagate errors. I needed the error propagation to collect errors from converter invocations.

**Comment by jeevatkm** [comment]
@rmohr I'm planning to merge this PR.

I would like to confirm, did you get a chance to test it real-time?

Also can you please take care of git conflicts and squash all commits into one?

**Comment by rmohr** [comment]
Herer are some references where we use it in kubevirt:

Mapping different structs and also UUID to string:
https://github.com/kubevirt/kubevirt/blob/master/pkg/api/v1/types.go#L52

Some generic mapping code based on this feature:
https://github.com/kubevirt/kubevirt/blob/master/pkg/util/mapper.go

Will rebase and squash everyting after the comming weekend.

**Comment by jeevatkm** [comment]
@rmohr  Thank you for reference.

Can you please take care of `model_test.go` conflict and squash commits? Then I will straight away merge your PR.

If I do it, your commits will go under my user Id, I would like to keep yours.

**Comment by rmohr** [comment]
@jeevatkm done

**Comment by jeevatkm** [comment]
Thank you @rmohr

**Pull request merged**
